import { get, post } from '@/request/index'
export const createOrder = (d: { item_id:number;start_date:string;end_date:string }) => post('/orders', d)
export const listOrders = (p?: any) => get('/orders', p)
export const getOrder = (id: number) => get(`/orders/${id}`, undefined)
export const pickup = (id: number) => post(`/orders/${id}/pickup`)
export const returnRequest = (id: number) => post(`/orders/${id}/return_request`)
export const returnConfirm = (id: number) => post(`/orders/${id}/return_confirm`)
export const breach = (id: number) => post(`/orders/${id}/breach`)
export const cancel = (id: number) => post(`/orders/${id}/cancel`)
export const refund = (order_id: number, amount: number) => post('/pay/refund', { order_id, refund_amount: amount })
